name: Next.js Docker Deploy

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Decide environment
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "ENV=production" >> $GITHUB_ENV
            echo "PORT=3019" >> $GITHUB_ENV
            echo "TAG=frontend-agricore-prod" >> $GITHUB_ENV
            echo "COMPOSE_FILE=docker-compose.prod.yml" >> $GITHUB_ENV
          else
            echo "ENV=" >> $GITHUB_ENV
            echo "PORT=3020" >> $GITHUB_ENV
            echo "TAG=frontend-agricore-dev" >> $GITHUB_ENV
            echo "COMPOSE_FILE=docker-compose.dev.yml" >> $GITHUB_ENV
          fi

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | \
          docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Debug env
        run: |
          echo "ENV=${{ env.ENV }}"
          echo "TAG=${{ env.TAG }}"


      - name: Build Docker image
        run: |
          echo "Building Docker image with ENV=${{ env.ENV }} and TAG=${{ env.TAG }}"
          docker build -t insurecow/insurecow_warehouse_repo:${{ env.TAG }} \
          --build-arg NODE_ENV=${{ env.ENV }} .

      - name: Push Docker image
        run: |
          docker push insurecow/insurecow_warehouse_repo:${{ env.TAG }}

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            whoami
            hostname
            cd /var/www/agricore
            docker pull insurecow/insurecow_warehouse_repo:${{ env.TAG }}
            docker compose -f ${{ env.COMPOSE_FILE }} up -d
